// <auto-generated />
namespace Coursmanager.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Class201911260948 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Class201911260948));
        
        string IMigrationMetadata.Id
        {
            get { return "201911260149098_Class201911260948"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
