// <auto-generated />
namespace Coursmanager.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Creat201911251034 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Creat201911251034));
        
        string IMigrationMetadata.Id
        {
            get { return "201911250234172_Creat201911251034"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
